version: '3'

services:
  db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: toor
       MYSQL_DATABASE: vulnspy
       MYSQL_USER: vulnspy
       MYSQL_PASSWORD: vulnspy
  web:
    depends_on:
      - db
    image: vsplate/phpmyadmin-4.8.1-allowarbitraryserver
    ports:
      - "80:80"
